### ISSUE TITLE
Add missing fields in RuntimeCR to avoid manual Shoot-Spec adjustments: DNS settings, Kubernetes configuration (autoscaler, kubeControllerMgr, kubeAPIServer)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma-infrastructure-manager#582]
**Description**

Some clusters include special configuration settings or hyperscaler specific adjustments (related to DNS or individual hyperscaler configurations), usually applied by SREs manually.

Goal is to avoid any manual adjustments in Shoot-Spec and cover all configuration parameters in the RuntimeCR and let them manage by KIM. SREs should be enabled to use RuntimeCR as single point for adjusting the ShootSpec.

SRE provided us a list of common cases where manually the Shoot-Spec was adjusted: https://github.com/kyma-project/infrastructure-manager/issues/407

* DNS configuration (e.g. `coreDNS` and `nodeLocalDNS`)
* Kubernetes configuration  (e.g. `clusterAutoscaler`,`kubeAPIServer` or `clusterControllerManager`)
* Worker-pool controller (`machineControllerManager`)

AC:
- [ ] POC: check which of the fields are configurable for SREs and can be supported by KIM (e.g. by adding these values to an existing Gardener cluster by editing the Shoot-Spec manually). See comments in #407 
    - [ ] DNS related configurations
    - [ ] configuration of the clusterAutoscaler
    - [ ] kubeAPiServer parameters
    - [ ] configuration for clusterControllerManager
    - [ ] configuration of machineControllerManager
- [ ] Write a work-plan how we introudce these fields and how the migration will be handed (e.g. using feature-flag per new field and migrate the data from productive Shoot-Specs into our RuntimeCR)
    - [ ] Align with SREs how these fields will be reflected in RuntimeCR
    - [ ] Setup a call with SRE and clarify how the migration for each field will happen:
       * Agree on a strategy for step-wise migration and its timelines
       * Clarify if any further risks exist (service interruptions etc.) 

**Reasons**

Add support for regularly manually adjusted fields to avoid manually applied misconfigurations.

**Attachments**

**Comment by tobiscr** [comment]
@ebensom  - can we agree that SREs are now able to configure everything of a Shoot within the RUntime CR ? 

If yes, we would close this topic.

**Comment by ebensom** [comment]
@tobiscr the current Runtime CR API still doesn'tz support configuring these aspects of the shoot: https://github.com/kyma-project/infrastructure-manager/issues/407#issuecomment-2447132217

**Comment by tobiscr** [comment]
Closing https://github.com/kyma-project/infrastructure-manager/issues/607 as duplicate of this issue
